[package]
name = "producer"
version = "0.1.0"
edition = "2021"

[dependencies]
mq = { path = "../mq" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"